version: '3.9'
services:
  redis:
    container_name: rediscontainer
    image: redis
    ports:
      - 6379:6379
  app:
    container_name: appcontainer
    image: redisapp:4
    ports:
      - 80:80
    depends_on:
      - redis