version: '3.9'
services:
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
  app:
    container_name: webapp
    image: webapp
    ports:
      - 80:80
    depends_on:
      - redis
